const state={id:"",version:0,view:null};
const $=s=>document.querySelector(s);
const formObject=form=>Object.fromEntries(new FormData(form).entries());
const number=(v)=>Number(v);
const key=()=>`web-${Date.now()}-${crypto.randomUUID()}`;

async function request(path,method="GET",body){
  const options={method,headers:{Accept:"application/json"}};
  if(body!==undefined){options.headers["Content-Type"]="application/json";options.headers["Idempotency-Key"]=key();options.body=JSON.stringify(body)}
  const response=await fetch(path,options);let data;
  try{data=await response.json()}catch{throw new Error(`服务返回了非 JSON 响应 (${response.status})`)}
  if(!response.ok){const e=data.error||{};markFieldIssues(e.fields||{});const fields=e.fields?"；"+Object.entries(e.fields).map(([k,v])=>`${k}: ${v}`).join("；"):"";throw new Error((e.message||"请求失败")+fields)}
  return data;
}
function notice(message,type="ok"){$("#notice").textContent=message;$("#notice").className=type;setTimeout(()=>{$("#notice").className=""},5000)}
async function act(path,body,message){
  if(!state.id)throw new Error("请先创建或载入评定");
  const data=await request(`/api/assessments/${state.id}${path}`,"POST",{expectedVersion:state.version,...body});
  applyView(data.assessment);notice(data.receipt.replayed?"已复用首次幂等提交结果":message);return data;
}
function applyView(view){
  state.view=view;state.id=view.assessment.id;state.version=view.assessment.version;
  $("#identity").textContent=`${view.assessment.lotCode} · ${view.assessment.status}`;$("#version").textContent=state.version;$("#status-dot").style.background="#c58b31";
  localStorage.setItem("seedgate.assessment",state.id);renderSteps();renderChecklist();renderReplicates();renderDeviations();renderMetrics();renderProgress();renderReviewItems();renderCertificate();renderAudit();
}
function renderSteps(){const order=["draft","protocol_frozen","observing","pending_review","returned","approved","sealed"];const pos=order.indexOf(state.view.assessment.status);document.querySelectorAll("#steps li").forEach(li=>{li.classList.toggle("active",order.indexOf(li.dataset.status)<=pos)})}
function renderChecklist(){$("#checklist").innerHTML=`<h3>当前检查清单</h3>${(state.view.checklist||[]).map(item=>`<div class="${item.complete?"done":"open"}"><b>${item.complete?"✓":"○"} ${escapeHTML(item.label)}</b><small>${escapeHTML(item.detail)}</small></div>`).join("")}`}
function renderReplicates(){
  const rows=[],options=[];const observations=state.view.observations||{};
  for(const r of state.view.replicates||[]){const history=observations[r.id]||[];const trail=history.map(o=>`D${o.dayNo}/R${o.revisionNo}: 正常${o.normalGerminated}`).join(" · ")||"尚无";rows.push(`<tr><td>${escapeHTML(r.label)}</td><td>${r.kind}</td><td>${r.status}</td><td>${escapeHTML(trail)}</td></tr>`);if(r.status!=="void")options.push(`<option value="${escapeHTML(r.id)}">${escapeHTML(r.label)} (${r.kind})</option>`)}
  $("#replicate-table").innerHTML=rows.join("");$("#replicate-select").innerHTML=options.join("");const activeOptions=(state.view.replicates||[]).filter(r=>r.status!=="void").map(r=>`<option value="${escapeHTML(r.id)}">${escapeHTML(r.label)}</option>`).join("");$("#affected-select").innerHTML=activeOptions;$("#review-replicates").innerHTML=activeOptions;
  $("#batch-day").innerHTML=(state.view.protocol?.observationDays||[]).map(day=>`<option value="${day}">D${day}</option>`).join("");
  $("#batch-observation-rows").innerHTML=(state.view.replicates||[]).filter(r=>r.status!=="void").map(r=>`<tr data-replicate="${escapeHTML(r.id)}"><td>${escapeHTML(r.label)}<small>${escapeHTML(r.kind)}</small></td>${["normalGerminated","abnormalSeedlings","hardSeeds","deadSeeds","ungerminatedSeeds"].map((field,index)=>`<td><input data-field="${field}" type="number" min="0" value="${index===0?r.sownQuantity:0}" required></td>`).join("")}</tr>`).join("");
}
function renderDeviations(){
  const b=state.view.sampleBoundary||{};$("#sample-boundary").textContent=`样本边界：送检 ${b.submittedQuantity||0} 粒；原始布置 ${b.originalUsed||0} 粒；复测已耗用 ${b.retestUsed||0} 粒；当前可用 ${b.available||0} 粒。`;
  $("#deviations").innerHTML=(state.view.deviations||[]).map(d=>`<div class="card">${d.status==="open"?`<button data-close="${escapeHTML(d.id)}" ${d.readyToClose?"":"disabled"}>闭环</button>`:""}<b>${escapeHTML(d.category)} · ${escapeHTML(d.id)}</b><br>${escapeHTML(d.description)}<br><small>作废 ${d.affectedReplicateIds.map(escapeHTML).join(", ")}；复测 ${d.retestReplicateIds.map(escapeHTML).join(", ")}；耗用 ${d.retestSeedQuantity||0} 粒</small>${d.status==="open"?`<p class="${d.readyToClose?"pass":"warning"}">${d.readyToClose?"全日程观测和当前指标已就绪":Object.entries(d.readinessIssues||{}).map(([field,message])=>`${escapeHTML(field)}：${escapeHTML(message)}`).join("；")}</p>`:""}</div>`).join("")||"<span class='empty'>无异常登记</span>";
  document.querySelectorAll("[data-close]").forEach(btn=>btn.onclick=()=>run(()=>act("/deviations/close",{deviationId:btn.dataset.close},"异常已闭环")));
}
function renderProgress(){const p=state.view.progress;if(!p?.days?.length){$("#progress").innerHTML="<p class='empty'>冻结方案后显示逐日发芽进程</p>";return}$("#progress").innerHTML=`<h3>逐日发芽进程与离群提示</h3><p class="hint">${escapeHTML(p.advisory)}</p><table><thead><tr><th>观察日</th><th>覆盖</th><th>平均正常发芽率</th><th>较前日增量</th><th>组间范围</th><th>缺失 / 提示</th></tr></thead><tbody>${p.days.map(d=>`<tr><td>D${d.dayNo}</td><td>${d.coveredGroups}/${d.effectiveGroups}</td><td>${d.averageNormalRate??"—"}${d.averageNormalRate==null?"":"%"}</td><td>${d.increment==null?"—":`${d.increment}%`}</td><td>${d.groupRange==null?"—":d.groupRange}</td><td>${d.missingReplicateIds.length?`缺失 ${d.missingReplicateIds.map(escapeHTML).join(", ")}`:"无缺失"}${d.outliers.map(o=>`<br><span class="warning">${escapeHTML(o.replicateLabel)} R${o.revisionNo}：${escapeHTML(o.message)}</span>`).join("")}</td></tr>`).join("")}</tbody></table>`}
function renderReviewItems(){const items=state.view.reviewItems||[];$("#review-items").innerHTML=items.map(item=>`<div class="card ${item.resolved?"resolved":""}"><b>${item.resolved?"✓ 已解决":"待补充"} · ${escapeHTML(item.evidenceArea)} · ${escapeHTML(item.id)}</b><br>${escapeHTML(item.problem)}<br><small>要求：${escapeHTML(item.requirement)}；退回版本 v${item.returnedVersion}${item.replicateIds?.length?`；关联 ${item.replicateIds.map(escapeHTML).join(", ")}`:""}</small>${item.resolved?`<p>完成说明：${escapeHTML(item.completionStatement)}（证据版本 v${item.resolvedVersion}）</p>`:`<p class="${item.canResolve?"pass":"warning"}">${escapeHTML(item.resolveBlocker)}</p><div class="resolve-row"><input data-resolution="${escapeHTML(item.id)}" placeholder="填写完成说明"><button data-resolve="${escapeHTML(item.id)}" ${item.canResolve?"":"disabled"}>核验并解决</button></div>`}</div>`).join("")||"<span class='empty'>无复核退回事项</span>";document.querySelectorAll("[data-resolve]").forEach(btn=>btn.onclick=()=>run(()=>act("/review/items/resolve",{itemId:btn.dataset.resolve,completionStatement:document.querySelector(`[data-resolution=\"${CSS.escape(btn.dataset.resolve)}\"]`).value},"退回事项已核验解决")))}
function renderMetrics(){
  const m=state.view.metrics;if(!m){$("#metrics").className="metric-grid empty";$("#metrics").textContent="完成所有有效组终止日观测后生成指标与规则明细";return}
  $("#metrics").className="metric-grid";$("#metrics").innerHTML=`<div class="metric">最终发芽率<b>${m.finalGerminationRate}%</b></div><div class="metric">重复组离散度<b>${m.dispersion}</b></div><div class="metric">阈值到达日<b>${m.thresholdDay||"未达到"}</b></div><div class="rules">${m.ruleHits.map(r=>`<div class="rule ${r.passed?"pass":"fail"}"><b>${r.passed?"✓":"×"} ${r.code}</b><span>${escapeHTML(r.message)}</span></div>`).join("")}</div>`;
}
function renderCertificate(){const c=state.view.certificate;if(!c){$("#certificate").className="certificate empty";$("#certificate").textContent="尚未生成凭据";return}$("#certificate-number").value=c.certificateNo;const v=state.view.certificateVerification;showCertificate(c,v?.valid??false,v?.message||"等待一致性校验",v)}
function showCertificate(c,valid,message,verification){$("#certificate").className="certificate";$("#certificate").innerHTML=`<h3>${valid?"✓ 凭据有效":"× 凭据无效"}</h3><p>${escapeHTML(message)}</p>${verification?`<p><small>${escapeHTML(verification.algorithm)} · ${escapeHTML(verification.checkedAt)}</small></p><div class="verification-items">${verification.items.map(item=>`<div class="${item.passed?"pass":"fail"}"><b>${item.passed?"✓":"×"} ${escapeHTML(item.code)}</b> ${escapeHTML(item.message)}</div>`).join("")}</div>`:""}<dl><dt>凭据编号</dt><dd>${escapeHTML(c.certificateNo)}</dd><dt>评定编号</dt><dd>${escapeHTML(c.assessmentId)}</dd><dt>结论</dt><dd>${escapeHTML(c.decision)}</dd><dt>最终发芽率</dt><dd>${c.finalGerminationRate}%</dd><dt>复核员</dt><dd>${escapeHTML(c.reviewedBy)}</dd><dt>方案摘要</dt><dd>${escapeHTML(c.protocolDigest)}</dd><dt>输入摘要</dt><dd>${escapeHTML(c.inputDigest)}</dd><dt>事件链摘要</dt><dd>${escapeHTML(c.eventChainDigest)}</dd><dt>凭据摘要</dt><dd>${escapeHTML(c.certificateDigest)}</dd></dl>`}
function renderAudit(){$("#audit").innerHTML=(state.view.audit||[]).slice().reverse().map(e=>`<div class="event"><b>v${e.version} · ${escapeHTML(e.type)}</b><br><small>${escapeHTML(e.occurredAt)}</small></div>`).join("")}
function escapeHTML(v){return String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]))}
function selectedValues(select){return [...select.selectedOptions].map(option=>option.value)}
function markFieldIssues(fields){document.querySelectorAll(".field-error").forEach(element=>element.classList.remove("field-error"));for(const key of Object.keys(fields)){const match=key.match(/^replicates\.([^.]*)\.([^.]*)/);if(match){const row=document.querySelector(`[data-replicate=\"${CSS.escape(match[1])}\"]`);row?.querySelector(`[data-field=\"${CSS.escape(match[2])}\"]`)?.classList.add("field-error");row?.classList.add("field-error")}}}
async function run(fn){try{await fn()}catch(error){notice(error.message,"error")}}

$("#create-form").addEventListener("submit",e=>run(async()=>{e.preventDefault();const v=formObject(e.currentTarget);const data=await request("/api/assessments","POST",{lotCode:v.lotCode,speciesName:v.speciesName,harvestYear:number(v.harvestYear),submittedQuantity:number(v.submittedQuantity),pretreatmentBoundary:v.pretreatmentBoundary});applyView(data.assessment);notice("评定已创建，批次边界已登记")}));
$("#load-form").addEventListener("submit",e=>run(async()=>{e.preventDefault();const id=$("#load-id").value.trim();applyView(await request(`/api/assessments/${encodeURIComponent(id)}`));notice("评定已恢复")}));
$("#protocol-form").addEventListener("submit",e=>run(async()=>{e.preventDefault();const v=formObject(e.currentTarget);await act("/protocol/freeze",{replicateCount:number(v.replicateCount),seedsPerReplicate:number(v.seedsPerReplicate),temperatureMinC:number(v.temperatureMinC),temperatureMaxC:number(v.temperatureMaxC),observationDays:v.observationDays.split(",").map(x=>number(x.trim())),terminationDay:number(v.terminationDay),minimumGerminationRate:number(v.minimumGerminationRate),maximumDispersion:number(v.maximumDispersion)},"试验方案快照已冻结")}));
$("#place-btn").onclick=()=>run(async()=>{if(!state.view?.protocol)throw new Error("请先冻结方案");const p=state.view.protocol;const now=new Date().toISOString();const replicates=Array.from({length:p.replicateCount},(_,i)=>({id:`rep-${i+1}`,label:`R${i+1}`,sownQuantity:p.seedsPerReplicate,startedAt:now}));await act("/replicates",{replicates},"重复组已按方案布置")});
$("#start-btn").onclick=()=>run(()=>act("/start",{},"完整性核验通过，已开始观测"));
$("#observation-form").addEventListener("submit",e=>run(async()=>{e.preventDefault();const v=formObject(e.currentTarget);await act("/observations",{replicateId:v.replicateId,dayNo:number(v.dayNo),normalGerminated:number(v.normalGerminated),abnormalSeedlings:number(v.abnormalSeedlings),hardSeeds:number(v.hardSeeds),deadSeeds:number(v.deadSeeds),ungerminatedSeeds:number(v.ungerminatedSeeds),recordedBy:v.recordedBy},"观测已保存并进入修订轨迹")}));
$("#batch-observation-form").addEventListener("submit",e=>run(async()=>{e.preventDefault();const form=e.currentTarget;const observations=[...$("#batch-observation-rows").querySelectorAll("tr")].map(row=>({replicateId:row.dataset.replicate,...Object.fromEntries([...row.querySelectorAll("input")].map(input=>[input.dataset.field,number(input.value)]))}));const body={dayNo:number(form.elements.dayNo.value),recordedBy:form.elements.recordedBy.value,observations};const check=await request(`/api/assessments/${state.id}/observations`,"POST",{expectedVersion:state.version,...body,validateOnly:true});if(!check.valid){const fields=Object.fromEntries(check.issues.map(i=>[`replicates.${i.replicateId||"batch"}.${i.field}`,i.message]));markFieldIssues(fields);throw new Error(`整批预检未通过：${check.issues.map(i=>`${i.replicateId||"整批"}/${i.field} ${i.message}`).join("；")}`)}const data=await act("/observations",body,`${check.groupCount} 个重复组观测已原子保存`);notice(`批量保存 ${data.receipt.successfulGroups} 组；终止日${data.receipt.terminalReady?"已":"未"}齐备`) }));
$("#deviation-form").addEventListener("submit",e=>run(async()=>{e.preventDefault();const v=formObject(e.currentTarget);const affectedReplicateIds=selectedValues($("#affected-select"));if(!affectedReplicateIds.length)throw new Error("至少选择一个受影响重复组");await act("/deviations",{category:v.category,affectedReplicateIds,description:v.description,disposition:v.disposition},"异常已登记，定向复测组已创建")}));
$("#calculate-btn").onclick=()=>run(()=>act("/calculate",{},"资格指标与规则明细已计算"));
$("#review-form").addEventListener("click",e=>{if(!e.target.dataset.review)return;e.preventDefault();run(async()=>{const v=formObject(e.currentTarget);const body={reviewer:v.reviewer,reason:v.reason};if(e.target.dataset.review==="return")body.items=[{evidenceArea:v.evidenceArea,problem:v.problem,requirement:v.requirement,replicateIds:selectedValues($("#review-replicates"))}];await act(`/review/${e.target.dataset.review}`,body,e.target.dataset.review==="approve"?"结论已批准":"已退回并登记结构化事项")})});
$("#resubmit-form").addEventListener("submit",e=>run(async()=>{e.preventDefault();await act("/review/resubmit",{submittedBy:formObject(e.currentTarget).submittedBy},"补充事项核验完成，已再次送审")}));
$("#seal-btn").onclick=()=>run(()=>act("/seal",{},"不可变资格凭据已封存"));
$("#verify-form").addEventListener("submit",e=>run(async()=>{e.preventDefault();const no=$("#certificate-number").value.trim();const result=await request(`/api/certificates/${encodeURIComponent(no)}/verify`);showCertificate(result.certificate,result.valid,result.message,result);notice(result.message,result.valid?"ok":"error")}));
const remembered=localStorage.getItem("seedgate.assessment");if(remembered){$("#load-id").value=remembered;run(async()=>applyView(await request(`/api/assessments/${encodeURIComponent(remembered)}`)))}
